#!/bin/bash

# there must be only 1 parameter - name of file to be deleted
if [[ $# -ne 1 ]]; then
	echo "Invalid number of parameters"
	exit 1
fi

# check that file is in PWD
if [[ $1 =~ .*\/.* ]]; then
	echo "FIle must be in current directory"
	exit 2
fi

# check if file in this directory with this name exists
FILE="$PWD/$1"
if ! [[ -f $FILE ]]; then
	echo "File $FILE doesn't exists"
	exit 2
fi

# if trash-bin doesn't exist create it with COUNT and LOG files
TRASH="/home/.trash"
TRASH_LOG="/home/.trash.log"
TRASH_COUNT="/home/.trash.count"
if ! [[ -d $TRASH ]]; then
	mkdir $TRASH
	rm -f $TRASH_LOG; touch $TRASH_LOG
	rm -f $TRASH_COUNT; echo 0 > $TRASH_COUNT
fi

# create new link and remove old file
COUNT=$(cat $TRASH_COUNT)
LINK="$TRASH/$COUNT"
ln $FILE $LINK &&
{
	COUNT=$(($COUNT + 1))
	echo $COUNT > $TRASH_COUNT
	echo "$FILE $LINK" > $TRASH_LOG

	rm -f $FILE

	echo "File $1 moved to trash bin"
}

exit 0
	


