#!/bin/bash

# check correctness of given parameter
if [[ $# -eq 0 ]]; then
	echo "Error: invalid number of parameters"
	exit 1
fi

if [[ "$@" =~ .*\/.* ]]; then
	echo "Error: path given instead of file name"
	exit 1
fi

TRASH="/home/.trash"
TRASH_LOG="/home/.trash.log"
TRASH_COUNT="home/.trash.count"

if ! [[ -f $TRASH_LOG ]] || ! [[ -d $TRASH ]]; then
	echo "Error: trash bin files corrupted, impossible to restore file"
	exit 2
fi

ls -1 "$TRASH" | while read -r NUMBER; do
	LINE=$(grep -E -w ".*\/$NUMBER" $TRASH_LOG)
	TRASH_PATH=$(echo "$LINE" | awk '{print $(NF)}')
	ORIGIN_PATH=$(echo "$LINE" | awk '{$(NF)=""; print $0}' | sed 's/.$//')
	FILENAME=$(echo "$ORIGIN_PATH" | grep -E -o "\/[^\/]+$" | sed 's/^.//')

#	echo "$LINE"
#	echo "$TRASH_PATH"
#	echo "$ORIGIN_PATH"
#	echo "$FILENAME"

	# check file's original name
	if ! [[ "$FILENAME" == "$@" ]]; then
		continue
	fi

	# ask if the file should be restored
	while true; do
		read -r -p "Do you want to restore $ORIGIN_PATH? [y/n]: " ANSWER < /dev/tty
		case $ANSWER in
			[Yy]* | [Nn]*)
				break
				;;
			*)
				echo "Error: invalid answer format"
				;;
		esac
	done

	# restore file if answer is positive (starts with Y/y)
	if [[ $ANSWER =~ ^[Yy]+.* ]]; then
		RESTORE_DIR=$(echo "$ORIGIN_PATH" | grep -E -o ".*\/" | sed 's/.$//')

		# check if restore directory still exists
		if ! [[ -d "$RESTORE_DIR" ]]; then
			echo "INFO: $RESTORE_DIR doesn't exists, file will be restored in /home"
			$RESTORE_DIR="/home"
		fi

		RESTORE_PATH="$RESTORE_DIR/$FILENAME"

		# check if there a name conflict in restore directory
		while [[ -f "$RESTORE_PATH" ]]; do
			read -r -p "File with name $FILENAME already exists in $RESTORE_DIR, please enter a new name: " NEW_NAME < /dev/tty
			if [[ $NEW_NAME =~ .*\/.* ]]; then
				echo "Error: invalid file name"
			else
				FILENAME="$NEW_NAME"
				RESTORE_PATH="$RESTORE_DIR/$FILENAME"
			fi
		done

		# restore file
		ln "$TRASH_PATH" "$RESTORE_PATH" &&
		{
			rm -f "$TRASH_PATH"
			echo "File $1 restored as $FILENAME in $RESTORE_PATH"
		}
	fi
done
